language: rust
rust:
  - stable
matrix:
  include:
    - os: linux
      dist: xenial
compiler: clang
fast_finish: true
cache: cargo
sudo: true
addons:
  apt:
    packages:
      - autoconf2.13
branches:
  only:
    - master
script:
  - travis_wait 30 cargo build 
  - cargo test
  - ./target/debug/sp_wasm_tests
