language: rust
rust:
- stable
matrix:
  include:
  - os: linux
    dist: xenial
compiler: clang
fast_finish: true
cache:
  directories:
    - $HOME/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
sudo: true
addons:
  apt:
    packages:
    - autoconf2.13
before_script:
  - echo TAG=$TRAVIS_TAG, TRAVIS_OS_NAME=$TRAVIS_OS_NAME
  - rustup toolchain install stable
  - rustup component add rustfmt --toolchain stable
  - rustup component list --toolchain stable
  - rustup show
script:
  - cargo +stable fmt --all -- --check
  - travis_wait 30 cargo build --release
  - travis_wait 30 cargo build
  - travis_wait 30 cargo test --all
  - cargo run --bin sp_wasm_tests
before_deploy: |
  TARGET_DIR=releases/sp-wasm-${TRAVIS_OS_NAME}-${TRAVIS_TAG}
  mkdir -p "$TARGET_DIR"
  cp target/release/wasm-sandbox "$TARGET_DIR/"
  strip "$TARGET_DIR/wasm-sandbox"
  ls -la "$TARGET_DIR"
  (cd releases && tar czvf "sp-wasm-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz" "sp-wasm-${TRAVIS_OS_NAME}-${TRAVIS_TAG}")
deploy:
  provider: releases
  api_key:
    secure: IxyA3xUDn8h6ozRnsIcPgpQObLI6SAgE56J5Ti9ACcluAkjZSlJtPHlTnWLjBm3zapbTnNSfolWQRRsKt2dAqIt6UHOvDeZpV3H9uMARFJ6gUbM10J6l9+HRXob35vbWM6VHgD0nuCtD3Aivq4IklRdSgGPH3k94XHiJjcPnWxq1coLp9JXxdwMg5opD0yjE9UQ/kHeKYt8N8Il+M4TQoJcEs5ZYcIP5DDpb2Shpkk2vx/GKHMLWPR6/mTZvX98dSS8DFAeejQyEw1KrxCoUzso7nl4xxCc+JpZkruQS9U61cAfqM2P3Zl1iLB7/87okEG1ZWjHiqTuDb9By20CDLyKfmZOzYkZjA7iyXhC/ENnykaFVGwZvG+qZ1NubXIewbXOA7nPBoPDAB67BjhK8VNepdY1cI8GZlE34dNG7CWPNySZViUAKhX+6WeznzKhyVPbitDEUDyhl9OSSnJgWWmoRA0XusaiNGVh3BteQN3LiL/asz6VeR4d96UY5/ufDye4i99ISLFYwumZ6yKuYEUEZ8dV3j+Y8yXjq3/L9AKHicuQm3xZbOj/bO4jHDA2q9976hmk74JmIjYYAWlmogTKOwQC8+WMW58zknBZTg1H82IEANxVxXkcegqdVNXCJEFGcVkgTsLQ7/LURCSLhZL7M988oLUBh9Kl9o6vo8lI=
  file: releases/sp-wasm-*.*
  on:
    repo: golemfactory/sp-wasm
