language: rust
rust:
  - stable
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
compiler: clang
fast_finish: true
cache: cargo
sudo: true
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository ppa:phoerious/keepassxc -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install autoconf2.13 libsodium-dev -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf@2.13; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium; fi
branches:
  only:
    - master
script:
  - travis_wait 30 cargo build 
  - cargo test
  - ./target/debug/sp_wasm_tests
