trigger:
- master

pr:
- master

jobs:
- job: Build
  timeoutInMinutes: 360

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    shell: /bin/bash

  steps:
  - checkout: self
    fetchDepth: 50

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      rustup toolchain install stable
      rustup component add rustfmt --toolchain stable
    displayName: Install rust

  - script: |
      sudo apt-get install -y --no-install-recommends autoconf2.13
    displayName: Install build-deps

  - script: |
      cargo +stable fmt --all -- --check
    displayName: Rustfmt check

  - bash: |
      cargo build --release
    displayName: Cargo build release

  - bash: |
      cargo build
    displayName: Cargo build debug

  - script: |
      cargo test --all
    displayName: Cargo test
