[package]
name = "sp-wasm-lib"
version = "0.0.2"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
libc = "0.2"
mozjs = "0.10"
log = "0.4"
lazy_static = "1.3"
itertools = "0.8"
zbox = "0.6"
path-clean = "0.1"

[features]
debugmozjs = ["mozjs/debugmozjs"]
