[package]
name = "sp-wasm-tests"
version = "0.1.1"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
sp-wasm-engine = { path = "../sp-wasm-engine" }
sp-wasm-memfs = { path = "../sp-wasm-memfs" }

[[bin]]
name = "sp_wasm_tests"
path = "src/main.rs"