[package]
name = "sp-wasm-hostfs"
version = "0.2.2"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
libc = "0.2"
mozjs = "0.10"
log = "0.4"
lazy_static = "1.3"
path-clean = "0.1"
failure = "0.1"


[features]
debugmozjs = ["mozjs/debugmozjs"]
